# Generated by Django 4.2.2 on 2023-06-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='libro',
            name='publicacion',
            field=models.DateField(null=True, verbose_name='Publicacion'),
        ),
    ]
