# Generated by Django 2.1.15 on 2023-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_imagenusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
