# Generated by Django 4.2.2 on 2023-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_auto_20230702_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
