# Generated by Django 4.2.2 on 2023-07-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_imagenusuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.TextField(null=True, verbose_name='Precio'),
        ),
    ]
